- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600


- name: Upgrade packages
  apt: upgrade=yes

- name: Install required packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - git
    - python-pip
    - python-dev
    - supervisor
    - cmake
    - libusb-1.0-0-dev
    - libhamlib-utils
    - vorbis-tools


- user:
    name: satnogs
    comment: "Satnogs Rotator Client"

- name: Blacklist dvb_usb_rtl28xxu module
  kernel_blacklist: name=dvb_usb_rtl28xxu state=present

- name: Disable dvb_usb_rtl28xxu module
  modprobe: name=dvb_usb_rtl28xxu state=absent
  become: true

- name: Fetch SatNOGS rtl-sdr fork
  git: repo=https://github.com/satnogs/rtl-sdr.git dest=/root/rtl-sdr
  register: rtl_sdr_repository
  become: true

- name: Create rtl-sdr build directory
  file: state=directory path=/root/rtl-sdr/build
  become: true

- name: Build rtl-sdr
  command: "{{ item }} chdir=/root/rtl-sdr/build"
  become: true
  with_items:
    - cmake ..
    - make
  when: rtl_sdr_repository.changed

- name: Install rtl-sdr
  command: make install chdir=/root/rtl-sdr/build
  become: true
  when: rtl_sdr_repository.changed

- name: Update latest shared libraries
  command: ldconfig
  become: true
  when: rtl_sdr_repository.changed

- name: Copy udev rules
  command: cp /root/rtl-sdr/rtl-sdr.rules /etc/udev/rules.d
  become: true
  when: rtl_sdr_repository.changed

- name: Update udev rules
  command: udevadm trigger
  become: true
  when: rtl_sdr_repository.changed

- name: Install satnogs-client
  become: true
  become_user: satnogs
  git: repo=https://github.com/satnogs/satnogs-client.git dest=~/satnogs-client
  register: satnogs_client_repository
  notify:
    - Restart satnogs

- name: Setup supervisor for rotctld process
  become: true
  template: src="supervisor-rotctld.conf.j2" dest="/etc/supervisor/conf.d/rotctld.conf"
  notify:
    - Restart rotctld

- name: Setup supervisor for satnogs-poller process
  become: true
  template: src="supervisor-satnogs-poller.conf.j2" dest="/etc/supervisor/conf.d/satnogs.conf"
  notify:
    - Restart satnogs
